### ISSUE TITLE
Create a logger library - No need to understand the entire system

### ISSUE THREAD

**Issue by goldbergyoni** [practicajs/practica#23]
**🎯 Goal:** - Create a logger library that wraps reputable industry logger and add additional common features

**🤔 Requirements:**

- Choose a reputable industry logger, Pino and Winston seem to be on the top. [Read the vendor choosing guide](https://github.com/practicajs/practica/blob/main/docs/vendor-pick-guidelines.MD)
- Add log levels - Based on the current configuration, write to log only if the configuration.log-level instructs so (e.g. info, error)
- Enable pretty print for beautiful terminal messages during development
- Hunt for other great logger practices
- Write a few tests against it
- Optionally: include a comparison table that explains why you preferred this specific logger lib

**⚙️Tech instructions:**

- There is already a logger library ./code-templates/libraries/logger, it's just empty
- Remember to also run the generated solution tests to ensure nothing broke
- Consider it assigning a scoped name @practicajs/logger and publish to npm

**Comment by henarbel** [comment]
I'll take it
