### ISSUE TITLE
contribution-short-guide link broken in CONTRIBUTING.md file

### ISSUE THREAD

**Issue by vishal-sharma-369** [practicajs/practica#270]
# In the CONTRIBUTING.md file , the link for contribution-short-guide page in the below section is broken.

## Consider the shortened guide first

Every small change can make this repo much better. If you intend to contribute a relatively small change like documentation change, small code enhancement or anything that is small and obvious - start by reading the [shortened guide here](https://github.com/vishal-sharma-369/practica/blob/main/docs/docs/contribution/contribution-short-guide.md). As you'll expand your engagement with this repo, it might be a good idea to visit this long guide again

> Issue : Here the link for contribution-short-guide link is not working

**Comment by goldbergyoni** [comment]
Hey @vishal-sharma-369 🙋‍♂️, welcome.

Yes, just noted that. This is because the link is related with the [web version](https://practica.dev/contribution/contribution-long-guide), any idea how to make it work for both GitHub.com and a website?

**Comment by vishal-sharma-369** [comment]
# Updating the link for the (shortened-guide-here) would resolve the issue in the below section:

# Consider the shortened guide first
Every small change can make this repo much better. If you intend to contribute a relatively small change like documentation change, small code enhancement or anything that is small and obvious - start by reading the [shortened guide here](https://github.com/practicajs/practica/blob/main/docs/docs/contribution/contribution-short-guide). As you'll expand your engagement with this repo, it might be a good idea to visit this long guide again


> Issue : Link broken
> Solution : 
>Updating the source of shortened-guide-here file from "/docs/docs/contribution/contribution-short-guide" to "/docs/docs/contribution/contribution-short-guide.md" would resolve the issue.

> Adding .md extension at the end of source resolved the issue.

**Comment by goldbergyoni** [comment]
It works now 🎯🎈💪 @vishal-sharma-369 

Thanks!
