### ISSUE TITLE
🤖 Configure stale issues bot that closes old issues

### ISSUE THREAD

**Issue by goldbergyoni** [practicajs/practica#28]
**🎯 Goal:** - When an issue is been idle for too long, then a label is applied. After some additional time it will get closed

[Stale bot](https://github.com/marketplace/stale) seems like a great tool for the mission, are there any other options?

**Comment by perilevy** [comment]
Hey @goldbergyoni, need permissions for configuring bots

**Comment by goldbergyoni** [comment]
See #29

**Comment by RonDaha** [comment]
Started to implement Stale bot
