### ISSUE TITLE
🤖 Make the CI run against multiple versions of Node (Matrix)

### ISSUE THREAD

**Issue by goldbergyoni** [practicajs/practica#54]
**🎯 Goal:** - Currently our CI runs against a specific Node.js version (e.g., the one within .nvmrc), since we should support also other Node.js versions like 12 & 14, it stands to reason to run the CI with all the supported versions of Node. GitHub actions support this out of the box

**🤔 More details:**

- Github actions support this with the [matrix feature](https://docs.github.com/en/github-ae@latest/actions/using-jobs/using-a-build-matrix-for-your-jobs)
- Test it - try temporarily embedding a feature that is supported only in Node.js 16, the CI should fail. Did it?
- Bonus: Besides Linux, put 'windows' OS as well in the matrix testing. It might fail, it's OK for now, at least our CI is ready

**Comment by alonkishoni** [comment]
took the issue
