### ISSUE TITLE
🤖 Request more info bot

### ISSUE THREAD

**Issue by goldbergyoni** [practicajs/practica#81]
**🎯 Goal:** - [Having a bot](https://github.com/apps/request-info) working for us when someone is opening a PR without sufficient details, the bot will ask for more info and prevent wasting the maintainer's time

**🤔 Things to consider:**

- If you need permissions for the installation phase, just ask and it will happen quickly
- Phrase a kind message to the opener who was just mistaken
- Test it!:)

**Comment by idobetesh** [comment]
Hi @goldbergyoni , please approve my request to add the request-info bot
